name: Build Rust Wrapper

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Staging branch to run release from"

env:
  RELEASE_TURBO_CLI: true
  RUST_BACKTRACE: full

jobs:
  build_static_linux_binary:
    name: "Build static Linux binary"
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - run: apk add git go protoc build-base clang rustup cargo gcc musl-dev libtool g++
      - run: /usr/bin/rustup-init -y
      - run: rustup target add x86_64-unknown-linux-musl
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_go_lib.yml
          workflow_conclusion: success
          branch: staging-1.7.0-canary.6
          name: turbo-lib-alpine-${{ inputs.release_branch }}
          path: cli/libturbo
          if_no_artifact_found: fail
      - name: Build release binary
        run: RUSTFLAGS="-Ctarget-feature=+crt-static -Clink-self-contained=yes" cargo build --release -p turbo-mock --target x86_64-unknown-linux-musl
      - name: Strip binary from debug symbols
        run: strip target/x86_64-unknown-linux-musl/release/turbo-mock
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: turbo-mock-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/turbo*
